/* clang-format off */
#ifndef SLUG_IMK_DIR_INTERN_ROOT
#error Define SLUG_IMK_DIR_INTERN_ROOT to use slugs
#endif /* SLUG_IMK_DIR_INTERN_ROOT */

#ifndef SLUG_STRINGIFY
#define SLUG_XSTRINGIFY(x) #x
#define SLUG_STRINGIFY(x) SLUG_XSTRINGIFY(x)
#endif /* SLUG_IMK_HEADER_STR */

#define SLUG_IMK_DIR_BASE SLUG_IMK_DIR_INTERN_ROOT/base
  #define SLUG_IMK_HEADER_BASE   SLUG_STRINGIFY(SLUG_IMK_DIR_BASE/IMK_base.h)
  #define SLUG_IMK_HEADER_BOOL   SLUG_STRINGIFY(SLUG_IMK_DIR_BASE/IMK_bool.h)
  #define SLUG_IMK_HEADER_FLOATS SLUG_STRINGIFY(SLUG_IMK_DIR_BASE/IMK_floats.h)
  #define SLUG_IMK_HEADER_INTS   SLUG_STRINGIFY(SLUG_IMK_DIR_BASE/IMK_ints.h)
  #define SLUG_IMK_HEADER_MACROS SLUG_STRINGIFY(SLUG_IMK_DIR_BASE/IMK_macros.h)

#define SLUG_IMK_DIR_CORE SLUG_IMK_DIR_INTERN_ROOT/core
  #define SLUG_IMK_HEADER_CORE   SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_core.h)
  #define SLUG_IMK_HEADER_MEM    SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_mem.h)
  #define SLUG_IMK_HEADER_PARAMS SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_params.h)
  #define SLUG_IMK_HEADER_PTR    SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_ptr.h)
  #define SLUG_IMK_HEADER_STEAP  SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_steap.h)
  #define SLUG_IMK_HEADER_SCOPE  SLUG_STRINGIFY(SLUG_IMK_DIR_CORE/IMK_scope.h)

  #define SLUG_IMK_DIR_ERROR SLUG_IMK_DIR_CORE/error
    #define SLUG_IMK_HEADER_ERROR SLUG_STRINGIFY(SLUG_IMK_DIR_ERROR/IMK_error.h)
    #define SLUG_IMK_HEADER_ERRNO SLUG_STRINGIFY(SLUG_IMK_DIR_ERROR/IMK_errno.h)

  #define SLUG_IMK_DIR_IO SLUG_IMK_DIR_CORE/io
    #define SLUG_IMK_HEADER_ASSERT SLUG_STRINGIFY(SLUG_IMK_DIR_IO/IMK_assert.h)
    #define SLUG_IMK_HEADER_PRINTF SLUG_STRINGIFY(SLUG_IMK_DIR_IO/IMK_printf.h)

  #define SLUG_IMK_DIR_LOGGING SLUG_IMK_DIR_CORE/logging
    #define SLUG_IMK_HEADER_ANSI_STYLE SLUG_STRINGIFY(SLUG_IMK_DIR_LOGGING/IMK_ansi_style.h)
    #define SLUG_IMK_HEADER_LOG        SLUG_STRINGIFY(SLUG_IMK_DIR_LOGGING/IMK_log.h)
    #define SLUG_IMK_HEADER_MODLOG     SLUG_STRINGIFY(SLUG_IMK_DIR_LOGGING/IMK_modlog.h)

  #define SLUG_IMK_DIR_OPTRES SLUG_IMK_DIR_CORE/optres
    #define SLUG_IMK_HEADER_OPTION SLUG_STRINGIFY(SLUG_IMK_DIR_OPTRES/IMK_option.h)
    #define SLUG_IMK_HEADER_RESULT SLUG_STRINGIFY(SLUG_IMK_DIR_OPTRES/IMK_result.h)
