/* clang-format off */
#ifndef IMK_SLUG_ROOT_DIR
#error Define IMK_SLUG_ROOT_DIR to use slugs
#endif /* IMK_SLUG_ROOT_DIR */

#ifndef IMK_SLUG_STRINGIFY
#define IMK_SLUG_XSTRINGIFY(x) #x
#define IMK_SLUG_STRINGIFY(x) IMK_SLUG_XSTRINGIFY(x)
#endif /* IMK_SLUG_STR */

#define IMK_SLUG_BASE_DIR IMK_SLUG_ROOT_DIR/base
  #define IMK_SLUG_BASE   IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_base.h)
  #define IMK_SLUG_BOOL   IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_bool.h)
  #define IMK_SLUG_FLOATS IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_floats.h)
  #define IMK_SLUG_INTS   IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_ints.h)
  #define IMK_SLUG_MACROS IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_macros.h)
  #define IMK_SLUG_TYPES  IMK_SLUG_STRINGIFY(IMK_SLUG_BASE_DIR/IMK_types.h)

#define IMK_SLUG_CORE_DIR IMK_SLUG_ROOT_DIR/core
  #define IMK_SLUG_MEM    IMK_SLUG_STRINGIFY(IMK_SLUG_CORE_DIR/IMK_mem.h)
  #define IMK_SLUG_PARAMS IMK_SLUG_STRINGIFY(IMK_SLUG_CORE_DIR/IMK_params.h)
  #define IMK_SLUG_PTR    IMK_SLUG_STRINGIFY(IMK_SLUG_CORE_DIR/IMK_ptr.h)
  #define IMK_SLUG_STEAP  IMK_SLUG_STRINGIFY(IMK_SLUG_CORE_DIR/IMK_steap.h)
  #define IMK_SLUG_SCOPE  IMK_SLUG_STRINGIFY(IMK_SLUG_CORE_DIR/IMK_scope.h)

  #define IMK_SLUG_ERROR_DIR IMK_SLUG_CORE_DIR/error
    #define IMK_SLUG_ERROR IMK_SLUG_STRINGIFY(IMK_SLUG_ERROR_DIR/IMK_error.h)
    #define IMK_SLUG_ERRNO IMK_SLUG_STRINGIFY(IMK_SLUG_ERROR_DIR/IMK_errno.h)

  #define IMK_SLUG_IO_DIR IMK_SLUG_CORE_DIR/io
    #define IMK_SLUG_ASSERT IMK_SLUG_STRINGIFY(IMK_SLUG_IO_DIR/IMK_assert.h)
    #define IMK_SLUG_PRINTF IMK_SLUG_STRINGIFY(IMK_SLUG_IO_DIR/IMK_printf.h)

  #define IMK_SLUG_LOGGING_DIR IMK_SLUG_CORE_DIR/logging
    #define IMK_SLUG_ANSI_STYLE IMK_SLUG_STRINGIFY(IMK_SLUG_LOGGING_DIR/IMK_ansi_style.h)
    #define IMK_SLUG_LOG        IMK_SLUG_STRINGIFY(IMK_SLUG_LOGGING_DIR/IMK_log.h)
    #define IMK_SLUG_MODLOG     IMK_SLUG_STRINGIFY(IMK_SLUG_LOGGING_DIR/IMK_modlog.h)

  #define IMK_SLUG_OPTRES_DIR IMK_SLUG_CORE_DIR/optres
    #define IMK_SLUG_OPTION IMK_SLUG_STRINGIFY(IMK_SLUG_OPTRES_DIR/IMK_option.h)
    #define IMK_SLUG_RESULT IMK_SLUG_STRINGIFY(IMK_SLUG_OPTRES_DIR/IMK_result.h)
