#define IMK_SLUG_EXTERN_ROOT_DIR imklib
#include "imklib/IMK_slug_index_ref.h"

#include IMK_SLUG_PTR
#include IMK_SLUG_OPTION

IMK_OPTION_DEFINE(IMK_OptVoid, int)
IMK_OPTION_DEFINE(IMK_OptInt, int)
IMK_OPTION_DEFINE(IMK_OptShort, short)
IMK_OPTION_DEFINE(IMK_OptLong, long)
IMK_OPTION_DEFINE(IMK_OptFloat, float)
IMK_OPTION_DEFINE(IMK_OptDouble, double)
IMK_OPTION_DEFINE(IMK_OptChar, char)
IMK_OPTION_DEFINE(IMK_OptUInt, unsigned int)
IMK_OPTION_DEFINE(IMK_OptUShort, unsigned short)
IMK_OPTION_DEFINE(IMK_OptULong, unsigned long)
IMK_OPTION_DEFINE(IMK_OptUChar, unsigned char)
IMK_OPTION_DEFINE(IMK_OptRPtr, void *)
IMK_OPTION_DEFINE(IMK_OptPtr, IMK_Ptr)
IMK_OPTION_DEFINE(IMK_OptS8, s8)
IMK_OPTION_DEFINE(IMK_OptS16, s16)
IMK_OPTION_DEFINE(IMK_OptS32, s32)
IMK_OPTION_DEFINE(IMK_OptS64, s64)
IMK_OPTION_DEFINE(IMK_OptU8, u8)
IMK_OPTION_DEFINE(IMK_OptU16, u16)
IMK_OPTION_DEFINE(IMK_OptU32, u32)
IMK_OPTION_DEFINE(IMK_OptU64, u64)
IMK_OPTION_DEFINE(IMK_OptF32, f32)
IMK_OPTION_DEFINE(IMK_OptF64, f64)
