#include "imklib/core/IMK_ptr.h"
#include "imklib/optres/IMK_option.h"
#include "imklib/optres/IMK_result.h"

IMK_OPTION_DEFINE(IMK_OptVoid, int)
IMK_OPTION_DEFINE(IMK_OptInt, int)
IMK_OPTION_DEFINE(IMK_OptShort, short)
IMK_OPTION_DEFINE(IMK_OptLong, long)
IMK_OPTION_DEFINE(IMK_OptFloat, float)
IMK_OPTION_DEFINE(IMK_OptDouble, double)
IMK_OPTION_DEFINE(IMK_OptChar, char)
IMK_OPTION_DEFINE(IMK_OptUInt, unsigned int)
IMK_OPTION_DEFINE(IMK_OptUShort, unsigned short)
IMK_OPTION_DEFINE(IMK_OptULong, unsigned long)
IMK_OPTION_DEFINE(IMK_OptUChar, unsigned char)
IMK_OPTION_DEFINE(IMK_OptRPtr, void *)
IMK_OPTION_DEFINE(IMK_OptPtr, IMK_Ptr)
IMK_OPTION_DEFINE(IMK_OptS8, s8)
IMK_OPTION_DEFINE(IMK_OptS16, s16)
IMK_OPTION_DEFINE(IMK_OptS32, s32)
IMK_OPTION_DEFINE(IMK_OptS64, s64)
IMK_OPTION_DEFINE(IMK_OptU8, u8)
IMK_OPTION_DEFINE(IMK_OptU16, u16)
IMK_OPTION_DEFINE(IMK_OptU32, u32)
IMK_OPTION_DEFINE(IMK_OptU64, u64)
IMK_OPTION_DEFINE(IMK_OptF32, f32)
IMK_OPTION_DEFINE(IMK_OptF64, f64)

IMK_RESULT_DEFINE(IMK_ResVoid, int, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResInt, int, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResShort, short, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResLong, long, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResFloat, float, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResDouble, double, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResChar, char, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResUInt, unsigned int, IMK_Ptr, IMK_PtrToStr,
                  IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResUShort, unsigned short, IMK_Ptr, IMK_PtrToStr,
                  IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResULong, unsigned long, IMK_Ptr, IMK_PtrToStr,
                  IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResUChar, unsigned char, IMK_Ptr, IMK_PtrToStr,
                  IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResRPtr, void *, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResPtr, IMK_Ptr, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResS8, s8, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResS16, s16, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResS32, s32, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResS64, s64, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResU8, u8, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResU16, u16, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResU32, u32, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResU64, u64, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResF32, f32, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
IMK_RESULT_DEFINE(IMK_ResF64, f64, IMK_Ptr, IMK_PtrToStr, IMK_PtrDropR)
